name: Deploy to S3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build and export
        run: cd frontend && npm run build && npm run export

      - name: Deploy to S3
        run: |
          aws configure set aws_access_key_id AKIARZHZTH5LHWDUONPZ
          aws configure set aws_secret_access_key iHrWgdb/d723Kv0/OL2e4cXrVS4C4WkmKqUSPO2n
          aws s3 sync frontend/out/ s3://your-bucket-name
